name: Final Challenge

on: [pull_request, main, branches: [main]]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: "ZeroOps Production"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v5"
        with: {python-version: '3.11'}
      - run: |
          pip install pytest
          echo "$PROJECT_NAME"
          python -m pytest
          echo "The testing was successfull"
